package ru.stqa.java_course.addressbook.tests;// Generated by Selenium IDE

import org.junit.Test;

public class GroupDeletionTests extends TestBase {
  @Test
  public void groupDeletionTests() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteSelectedGroups();
    app.getGroupHelper().returnGroupPage();
  }

}
