package ru.stqa.java_course.addressbook.tests;// Generated by Selenium IDE
import org.junit.Test;
import ru.stqa.java_course.addressbook.model.GroupData;

public class GroupCreationTests extends TestBase {

  @Test
  public void testgroupCreation() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().initGroupCreation();
    app.getGroupHelper().fillGroupForm(new GroupData("test1", "test2", "test3"));
    app.getGroupHelper().submitGroupCreation();
    app.getGroupHelper().returnGroupPage();

  }

}
